drop table if exists sys_user;

CREATE TABLE sys_user
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_name VARCHAR(255) UNIQUE,
    password  VARCHAR(255),
    nick_name VARCHAR(255),
    status    VARCHAR(255)
);

CREATE TABLE sys_platform
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    platform_url VARCHAR(255),
    user_name    VARCHAR(255),
    password     VARCHAR(255),
    mqtt_broker  VARCHAR(500) -- 假设 MqttBrokerConfig 可以转换为字符串
);